### ISSUE TITLE
a4 div

### ISSUE THREAD

**Issue by franfranfranfran** [Blackwonderland/prj-rev-bwfs-dasmoto#1]
https://github.com/Blackwonderland/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26crafts/home.html#L8

hm, good idea to play around with sizing and structure on the page, but i dont think it adds much to restrict the entirety of the content to a very small portion in the middle of the screen. consider letting everything take up the full width

also note that nothing should be outside of the body tags

**Comment by Blackwonderland** [comment]
Hm okay. I just don't like this long stretched text lines and don't know yet how to make it look more attractive.
