### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [Blackwonderland/prj-rev-bwfs-dasmoto#5]
**GRADE**: Needs Improvement

**SUMMARY**: Great start on this project. With a few small tweaks, the page will be looking great and you've done an excellent job keeping the project folder organized by using the separate resources folder. 

Behind the scenes, there's just a few areas to look at to make sure everything is perfect. Consider restructuring your divs a bit to emphasize the main content sections. Use them to group chunks of content together and make the page as a whole more organized. Also, make sure to keep your indentation as consistent as possible. Everything that is nested to the same level should be indented the same to indicate that relationship. 

As a next step try saving your image files locally to an images folder inside of resources and then use relative file paths to link to those from your html and css. The link to css on line 6 of your html is a great example and more info can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/).

Have fun and keep up the good work!

**Comment by Blackwonderland** [comment]
Thanks a lot :) quick question regarding indentation: let's say I have a div with a h1, h2 and p.. Would it look like this:
Div
  H1
    H2
      P
/div
Or like this:
Div
  H1
  H2
  P
/div
?

**Comment by Blackwonderland** [comment]
Oh it removed the white space
